"""Constants for the HelvarNet integration."""

DOMAIN = "helvar"

CONF_HOST = "host"
CONF_PORT = "port"

DEFAULT_PORT = 50000

DEFAULT_ON_GROUP_SCENE = 1
DEFAULT_ON_GROUP_BLOCK = 1
DEFAULT_OFF_GROUP_BLOCK = 1
DEFAULT_OFF_GROUP_SCENE = 15
VALID_OFF_GROUP_SCENES = (15, 16)
